services:
  db:
    image: postgres:13
    container_name: ccdoc-postgres
    environment:
      POSTGRES_DB: odoo
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo_pwd_local
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    platform: linux/arm64

  odoo:
    image: odoo:17.0
    container_name: ccdoc-odoo
    depends_on:
      - db
    ports:
      - "8069:8069"
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo_pwd_local
    volumes:
      - odoo_data:/var/lib/odoo
      - ./custom_addons:/mnt/extra-addons
      - ./config:/etc/odoo
    restart: unless-stopped
    platform: linux/arm64

volumes:
  postgres_data:
  odoo_data: